<?php

namespace App\Service;

use App\Entity\Trip;
use Endroid\QrCode\Encoding\Encoding;
use Endroid\QrCode\ErrorCorrectionLevel;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\RoundBlockSizeMode;
use Endroid\QrCode\Writer\PngWriter;
use Endroid\QrCode\Writer\Result\ResultInterface;
use Endroid\QrCode\Writer\SvgWriter;

class TripQrCodeService
{
    /**
     * @return array{content: string, mimeType: string}
     */
    public function buildTripQrImage(Trip $trip, string $tripUrl): array
    {
        $result = $this->writeQrResult($trip, $tripUrl);

        return [
            'content' => $result->getString(),
            'mimeType' => $result->getMimeType(),
        ];
    }

    public function buildTripQrDataUri(Trip $trip, string $tripUrl): string
    {
        return $this->writeQrResult($trip, $tripUrl)->getDataUri();
    }

    private function writeQrResult(Trip $trip, string $tripUrl): ResultInterface
    {
        $payload = $this->buildPayload($trip, $tripUrl);

        $qrCode = new QrCode(
            data: $payload,
            encoding: new Encoding('UTF-8'),
            errorCorrectionLevel: ErrorCorrectionLevel::Medium,
            size: 280,
            margin: 10,
            roundBlockSizeMode: RoundBlockSizeMode::Margin,
        );

        try {
            // Prefer PNG when GD is available for broad compatibility.
            return (new PngWriter())->write($qrCode);
        } catch (\Throwable) {
            // Fallback for environments without GD extension.
            return (new SvgWriter())->write($qrCode);
        }
    }

    private function buildPayload(Trip $trip, string $tripUrl): string
    {
        $startDate = $trip->getStartDate()?->format('Y-m-d') ?? '-';
        $endDate = $trip->getEndDate()?->format('Y-m-d') ?? '-';
        $budget = sprintf(
            '%s %s',
            trim($trip->getCurrency()),
            number_format((float) ($trip->getBudgetAmount() ?? 0.0), 2, '.', ',')
        );

        return implode("\n", [
            'TravelXP Trip Summary',
            sprintf('Name: %s', trim((string) $trip->getTripName())),
            sprintf('Route: %s -> %s', trim((string) ($trip->getOrigin() ?? '-')), trim((string) ($trip->getDestination() ?? '-'))),
            sprintf('Dates: %s to %s', $startDate, $endDate),
            sprintf('Status: %s', trim($trip->getStatus())),
            sprintf('Budget: %s', $budget),
            sprintf('Participants: %d', $trip->getParticipants()->count()),
            sprintf('Seats: %d/%d available', (int) $trip->getAvailableSeats(), (int) $trip->getTotalCapacity()),
            'Generated by TravelXP',
        ]);
    }
}
