<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O9dFrnPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o9dFrnP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'property' => ['privates', '.errored..service_locator.o9dFrnP.App\\Entity\\Property', NULL, 'Cannot autowire service ".service_locator.o9dFrnP": it needs an instance of "App\\Entity\\Property" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'property' => 'App\\Entity\\Property',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.o9dFrnP'])) {
            return $container->privates['.service_locator.o9dFrnP'];
        }

        return $container->privates['.service_locator.o9dFrnP'] = $instance;
    }
}
