<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OllXBORService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OllXBOR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trip' => ['privates', '.errored..service_locator.OllXBOR.App\\Entity\\Trip', NULL, 'Cannot autowire service ".service_locator.OllXBOR": it needs an instance of "App\\Entity\\Trip" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'trip' => 'App\\Entity\\Trip',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.OllXBOR'])) {
            return $container->privates['.service_locator.OllXBOR'];
        }

        return $container->privates['.service_locator.OllXBOR'] = $instance;
    }
}
