<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6nH6szSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6nH6szS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activity' => ['privates', '.errored..service_locator.6nH6szS.App\\Entity\\Activity', NULL, 'Cannot autowire service ".service_locator.6nH6szS": it needs an instance of "App\\Entity\\Activity" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'activity' => 'App\\Entity\\Activity',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.6nH6szS'])) {
            return $container->privates['.service_locator.6nH6szS'];
        }

        return $container->privates['.service_locator.6nH6szS'] = $instance;
    }
}
