<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HbI_MKiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HbI.mKi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'quest' => ['privates', '.errored..service_locator.HbI.mKi.App\\Entity\\Quest', NULL, 'Cannot autowire service ".service_locator.HbI.mKi": it needs an instance of "App\\Entity\\Quest" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'quest' => 'App\\Entity\\Quest',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.HbI.mKi'])) {
            return $container->privates['.service_locator.HbI.mKi'];
        }

        return $container->privates['.service_locator.HbI.mKi'] = $instance;
    }
}
