<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminGamificationControllernewQuestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3BoFVFw.App\Controller\AdminGamificationController::newQuest()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.3BoFVFw'] ?? $container->load('get_ServiceLocator_3BoFVFwService'));

        if (isset($container->privates['.service_locator.3BoFVFw.App\\Controller\\AdminGamificationController::newQuest()'])) {
            return $container->privates['.service_locator.3BoFVFw.App\\Controller\\AdminGamificationController::newQuest()'];
        }

        $instance = $a->withContext('App\\Controller\\AdminGamificationController::newQuest()', $container);

        if (isset($container->privates['.service_locator.3BoFVFw.App\\Controller\\AdminGamificationController::newQuest()'])) {
            return $container->privates['.service_locator.3BoFVFw.App\\Controller\\AdminGamificationController::newQuest()'];
        }

        return $container->privates['.service_locator.3BoFVFw.App\\Controller\\AdminGamificationController::newQuest()'] = $instance;
    }
}
