<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HvcPVQS.App\Controller\ActivityController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HvcPVQS.App\\Controller\\ActivityController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activity' => ['privates', '.errored..service_locator.HvcPVQS.App\\Entity\\Activity', NULL, 'Cannot autowire service ".service_locator.HvcPVQS": it needs an instance of "App\\Entity\\Activity" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'activity' => 'App\\Entity\\Activity',
        ]))->withContext('App\\Controller\\ActivityController::show()', $container);
    }
}
