<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminGamificationControllereditUserGamificationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8m8R3s_.App\Controller\AdminGamificationController::editUserGamification()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.8m8R3s_.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.8m8R3s_": it needs an instance of "App\\Entity\\User" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\AdminGamificationController::editUserGamification()', $container);

        if (isset($container->privates['.service_locator.8m8R3s_.App\\Controller\\AdminGamificationController::editUserGamification()'])) {
            return $container->privates['.service_locator.8m8R3s_.App\\Controller\\AdminGamificationController::editUserGamification()'];
        }

        return $container->privates['.service_locator.8m8R3s_.App\\Controller\\AdminGamificationController::editUserGamification()'] = $instance;
    }
}
