<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eg7h5g1.App\Controller\ActivityController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eg7h5g1.App\\Controller\\ActivityController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activityRepository' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService', true],
        ], [
            'activityRepository' => 'App\\Repository\\ActivityRepository',
        ]))->withContext('App\\Controller\\ActivityController::index()', $container);
    }
}
