<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllersuggestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ChWumlx.App\Controller\BlogController::suggest()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ChWumlx.App\\Controller\\BlogController::suggest()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blogRepository' => ['privates', 'App\\Repository\\BlogRepository', 'getBlogRepositoryService', true],
        ], [
            'blogRepository' => 'App\\Repository\\BlogRepository',
        ]))->withContext('App\\Controller\\BlogController::suggest()', $container);
    }
}
