<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yW9QJGw.App\Controller\BlogController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blog' => ['privates', '.errored..service_locator.yW9QJGw.App\\Entity\\Blog', NULL, 'Cannot autowire service ".service_locator.yW9QJGw": it needs an instance of "App\\Entity\\Blog" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'profanityFilterService' => ['privates', 'App\\Service\\ProfanityFilterService', 'getProfanityFilterServiceService', true],
        ], [
            'blog' => 'App\\Entity\\Blog',
            'entityManager' => '?',
            'profanityFilterService' => 'App\\Service\\ProfanityFilterService',
        ]))->withContext('App\\Controller\\BlogController::edit()', $container);

        if (isset($container->privates['.service_locator.yW9QJGw.App\\Controller\\BlogController::edit()'])) {
            return $container->privates['.service_locator.yW9QJGw.App\\Controller\\BlogController::edit()'];
        }

        return $container->privates['.service_locator.yW9QJGw.App\\Controller\\BlogController::edit()'] = $instance;
    }
}
