<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UxE8KIL.App\Controller\BookingController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.UxE8KIL'] ?? $container->load('get_ServiceLocator_UxE8KILService'));

        if (isset($container->privates['.service_locator.UxE8KIL.App\\Controller\\BookingController::edit()'])) {
            return $container->privates['.service_locator.UxE8KIL.App\\Controller\\BookingController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\BookingController::edit()', $container);

        if (isset($container->privates['.service_locator.UxE8KIL.App\\Controller\\BookingController::edit()'])) {
            return $container->privates['.service_locator.UxE8KIL.App\\Controller\\BookingController::edit()'];
        }

        return $container->privates['.service_locator.UxE8KIL.App\\Controller\\BookingController::edit()'] = $instance;
    }
}
