<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllersummarizeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wMS2WYE.App\Controller\BlogController::summarize()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wMS2WYE.App\\Controller\\BlogController::summarize()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blog' => ['privates', '.errored..service_locator.wMS2WYE.App\\Entity\\Blog', NULL, 'Cannot autowire service ".service_locator.wMS2WYE": it needs an instance of "App\\Entity\\Blog" but this type has been excluded because it\'s a Doctrine entity.'],
            'aiSummarizerService' => ['privates', 'App\\Service\\AiSummarizerService', 'getAiSummarizerServiceService', true],
        ], [
            'blog' => 'App\\Entity\\Blog',
            'aiSummarizerService' => 'App\\Service\\AiSummarizerService',
        ]))->withContext('App\\Controller\\BlogController::summarize()', $container);
    }
}
