<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3pOWNvw.App\Controller\BookingController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'propertyRepository' => ['privates', 'App\\Repository\\PropertyRepository', 'getPropertyRepositoryService', true],
        ], [
            'entityManager' => '?',
            'propertyRepository' => 'App\\Repository\\PropertyRepository',
        ]))->withContext('App\\Controller\\BookingController::new()', $container);

        if (isset($container->privates['.service_locator.3pOWNvw.App\\Controller\\BookingController::new()'])) {
            return $container->privates['.service_locator.3pOWNvw.App\\Controller\\BookingController::new()'];
        }

        return $container->privates['.service_locator.3pOWNvw.App\\Controller\\BookingController::new()'] = $instance;
    }
}
