<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerexportBlogPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.81_kRG6.App\Controller\BlogController::exportBlogPdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.81_kRG6.App\\Controller\\BlogController::exportBlogPdf()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blog' => ['privates', '.errored..service_locator.81_kRG6.App\\Entity\\Blog', NULL, 'Cannot autowire service ".service_locator.81_kRG6": it needs an instance of "App\\Entity\\Blog" but this type has been excluded because it\'s a Doctrine entity.'],
            'readTimeEstimator' => ['privates', 'App\\Service\\ReadTimeEstimatorService', 'getReadTimeEstimatorServiceService', true],
        ], [
            'blog' => 'App\\Entity\\Blog',
            'readTimeEstimator' => 'App\\Service\\ReadTimeEstimatorService',
        ]))->withContext('App\\Controller\\BlogController::exportBlogPdf()', $container);
    }
}
