<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PWlICch.App\Controller\BlogController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PWlICch.App\\Controller\\BlogController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blogRepository' => ['privates', 'App\\Repository\\BlogRepository', 'getBlogRepositoryService', true],
            'readTimeEstimator' => ['privates', 'App\\Service\\ReadTimeEstimatorService', 'getReadTimeEstimatorServiceService', true],
        ], [
            'blogRepository' => 'App\\Repository\\BlogRepository',
            'readTimeEstimator' => 'App\\Service\\ReadTimeEstimatorService',
        ]))->withContext('App\\Controller\\BlogController::index()', $container);
    }
}
