<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllertranslateCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._BhRMHU.App\Controller\CommentController::translateComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._BhRMHU.App\\Controller\\CommentController::translateComment()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'comment' => ['privates', '.errored..service_locator._BhRMHU.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator._BhRMHU": it needs an instance of "App\\Entity\\Comment" but this type has been excluded because it\'s a Doctrine entity.'],
            'translationService' => ['privates', 'App\\Service\\TranslationService', 'getTranslationServiceService', true],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'translationService' => 'App\\Service\\TranslationService',
        ]))->withContext('App\\Controller\\CommentController::translateComment()', $container);
    }
}
