<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfferControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CB9wWly.App\Controller\OfferController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CB9wWly.App\\Controller\\OfferController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'offer' => ['privates', '.errored..service_locator.CB9wWly.App\\Entity\\Offer', NULL, 'Cannot autowire service ".service_locator.CB9wWly": it needs an instance of "App\\Entity\\Offer" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'offer' => 'App\\Entity\\Offer',
        ]))->withContext('App\\Controller\\OfferController::show()', $container);
    }
}
