<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.87_m6dB.App\Controller\ProfileController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'tokenStorage' => '?',
        ]))->withContext('App\\Controller\\ProfileController::delete()', $container);

        if (isset($container->privates['.service_locator.87_m6dB.App\\Controller\\ProfileController::delete()'])) {
            return $container->privates['.service_locator.87_m6dB.App\\Controller\\ProfileController::delete()'];
        }

        return $container->privates['.service_locator.87_m6dB.App\\Controller\\ProfileController::delete()'] = $instance;
    }
}
