<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertyControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._CeB3dG.App\Controller\PropertyController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._CeB3dG.App\\Controller\\PropertyController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'propertyRepository' => ['privates', 'App\\Repository\\PropertyRepository', 'getPropertyRepositoryService', true],
            'currencyConverter' => ['privates', 'App\\Service\\CurrencyConverterService', 'getCurrencyConverterServiceService', true],
        ], [
            'propertyRepository' => 'App\\Repository\\PropertyRepository',
            'currencyConverter' => 'App\\Service\\CurrencyConverterService',
        ]))->withContext('App\\Controller\\PropertyController::index()', $container);
    }
}
