<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrip2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._bhMPIo.App\Entity\Trip' shared service.
     *
     * @return \App\Entity\Trip
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._bhMPIo": it needs an instance of "App\\Entity\\Trip" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
