<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripControllerjoinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OllXBOR.App\Controller\TripController::join()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.OllXBOR'] ?? $container->load('get_ServiceLocator_OllXBORService'));

        if (isset($container->privates['.service_locator.OllXBOR.App\\Controller\\TripController::join()'])) {
            return $container->privates['.service_locator.OllXBOR.App\\Controller\\TripController::join()'];
        }

        $instance = $a->withContext('App\\Controller\\TripController::join()', $container);

        if (isset($container->privates['.service_locator.OllXBOR.App\\Controller\\TripController::join()'])) {
            return $container->privates['.service_locator.OllXBOR.App\\Controller\\TripController::join()'];
        }

        return $container->privates['.service_locator.OllXBOR.App\\Controller\\TripController::join()'] = $instance;
    }
}
