# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.geoapify_map_tiles_api_key: '%env(string:GEOAPIFY_MAP_TILES_API_KEY)%'
    app.geoapify_autocomplete_api_key: '%env(string:GEOAPIFY_AUTOCOMPLETE_API_KEY)%'
    app.geoapify_places_api_key: '%env(string:GEOAPIFY_PLACES_API_KEY)%'
    app.geoapify_routing_api_key: '%env(string:GEOAPIFY_ROUTING_API_KEY)%'
    app.geoapify_map_tiles_url: '%env(string:GEOAPIFY_MAP_TILES_URL)%'
    app.geoapify_autocomplete_url: '%env(string:GEOAPIFY_AUTOCOMPLETE_URL)%'
    app.geoapify_places_url: '%env(string:GEOAPIFY_PLACES_URL)%'
    app.geoapify_routing_url: '%env(string:GEOAPIFY_ROUTING_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Service\GrammarService:
        arguments:
            $languageToolUrl: '%env(string:LANGUAGETOOL_URL)%'

    App\Service\TranslationService:
        arguments:
            $translateApiUrl: '%env(string:TRANSLATE_API_URL)%'

    App\Service\AiSummarizerService:
        arguments:
            $openAiApiKey: '%env(default::OPENAI_API_KEY)%'

    App\Service\GeminiAssistantService:
        arguments:
            $apiKey: '%env(string:GEMINI_API_KEY)%'
            $model: '%env(string:GEMINI_MODEL)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Controller\PropertyController:
        bind:
            $geoapifyMapTilesApiKey: '%app.geoapify_map_tiles_api_key%'
            $geoapifyMapTilesUrl: '%app.geoapify_map_tiles_url%'

    App\Service\GeoapifyService:
        bind:
            $autocompleteApiKey: '%app.geoapify_autocomplete_api_key%'
            $placesApiKey: '%app.geoapify_places_api_key%'
            $routingApiKey: '%app.geoapify_routing_api_key%'
            $autocompleteUrl: '%app.geoapify_autocomplete_url%'
            $placesUrl: '%app.geoapify_places_url%'
            $routingUrl: '%app.geoapify_routing_url%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
