<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UxE8KILService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UxE8KIL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'booking' => ['privates', '.errored..service_locator.UxE8KIL.App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.UxE8KIL": it needs an instance of "App\\Entity\\Booking" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'booking' => 'App\\Entity\\Booking',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.UxE8KIL'])) {
            return $container->privates['.service_locator.UxE8KIL'];
        }

        return $container->privates['.service_locator.UxE8KIL'] = $instance;
    }
}
