<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminGamificationControllereditQuestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HbI.mKi.App\Controller\AdminGamificationController::editQuest()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.HbI.mKi'] ?? $container->load('get_ServiceLocator_HbI_MKiService'));

        if (isset($container->privates['.service_locator.HbI.mKi.App\\Controller\\AdminGamificationController::editQuest()'])) {
            return $container->privates['.service_locator.HbI.mKi.App\\Controller\\AdminGamificationController::editQuest()'];
        }

        $instance = $a->withContext('App\\Controller\\AdminGamificationController::editQuest()', $container);

        if (isset($container->privates['.service_locator.HbI.mKi.App\\Controller\\AdminGamificationController::editQuest()'])) {
            return $container->privates['.service_locator.HbI.mKi.App\\Controller\\AdminGamificationController::editQuest()'];
        }

        return $container->privates['.service_locator.HbI.mKi.App\\Controller\\AdminGamificationController::editQuest()'] = $instance;
    }
}
