<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAiSummarizerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AiSummarizerService' shared autowired service.
     *
     * @return \App\Service\AiSummarizerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AiSummarizerService.php';

        return $container->privates['App\\Service\\AiSummarizerService'] = new \App\Service\AiSummarizerService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));
    }
}
