<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminGamificationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6aVPdPI.App\Controller\AdminGamificationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6aVPdPI.App\\Controller\\AdminGamificationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'questRepository' => ['privates', 'App\\Repository\\QuestRepository', 'getQuestRepositoryService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'questRepository' => 'App\\Repository\\QuestRepository',
        ]))->withContext('App\\Controller\\AdminGamificationController::index()', $container);
    }
}
