<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityControllerjoinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6nH6szS.App\Controller\ActivityController::join()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.6nH6szS'] ?? $container->load('get_ServiceLocator_6nH6szSService'));

        if (isset($container->privates['.service_locator.6nH6szS.App\\Controller\\ActivityController::join()'])) {
            return $container->privates['.service_locator.6nH6szS.App\\Controller\\ActivityController::join()'];
        }

        $instance = $a->withContext('App\\Controller\\ActivityController::join()', $container);

        if (isset($container->privates['.service_locator.6nH6szS.App\\Controller\\ActivityController::join()'])) {
            return $container->privates['.service_locator.6nH6szS.App\\Controller\\ActivityController::join()'];
        }

        return $container->privates['.service_locator.6nH6szS.App\\Controller\\ActivityController::join()'] = $instance;
    }
}
