<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nCI.zgr.App\Controller\BlogController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nCI.zgr.App\\Controller\\BlogController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blog' => ['privates', '.errored..service_locator.nCI.zgr.App\\Entity\\Blog', NULL, 'Cannot autowire service ".service_locator.nCI.zgr": it needs an instance of "App\\Entity\\Blog" but this type has been excluded because it\'s a Doctrine entity.'],
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'readTimeEstimator' => ['privates', 'App\\Service\\ReadTimeEstimatorService', 'getReadTimeEstimatorServiceService', true],
            'commentSentimentService' => ['privates', 'App\\Service\\CommentSentimentService', 'getCommentSentimentServiceService', true],
        ], [
            'blog' => 'App\\Entity\\Blog',
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'readTimeEstimator' => 'App\\Service\\ReadTimeEstimatorService',
            'commentSentimentService' => 'App\\Service\\CommentSentimentService',
        ]))->withContext('App\\Controller\\BlogController::show()', $container);
    }
}
