<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7KWuaOD.App\Entity\Blog' shared service.
     *
     * @return \App\Entity\Blog
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7KWuaOD": it needs an instance of "App\\Entity\\Blog" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
