<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllergrammarToolService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5fgY8sI.App\Controller\BlogController::grammarTool()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5fgY8sI.App\\Controller\\BlogController::grammarTool()'] = ($container->privates['.service_locator.5fgY8sI'] ?? $container->load('get_ServiceLocator_5fgY8sIService'))->withContext('App\\Controller\\BlogController::grammarTool()', $container);
    }
}
