<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bouXrYm.App\Controller\BlogController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blog' => ['privates', '.errored..service_locator.bouXrYm.App\\Entity\\Blog', NULL, 'Cannot autowire service ".service_locator.bouXrYm": it needs an instance of "App\\Entity\\Blog" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'blog' => 'App\\Entity\\Blog',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\BlogController::delete()', $container);

        if (isset($container->privates['.service_locator.bouXrYm.App\\Controller\\BlogController::delete()'])) {
            return $container->privates['.service_locator.bouXrYm.App\\Controller\\BlogController::delete()'];
        }

        return $container->privates['.service_locator.bouXrYm.App\\Controller\\BlogController::delete()'] = $instance;
    }
}
