<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerexportBlogCommentsPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VEHgvk6.App\Controller\BlogController::exportBlogCommentsPdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VEHgvk6.App\\Controller\\BlogController::exportBlogCommentsPdf()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blog' => ['privates', '.errored..service_locator.VEHgvk6.App\\Entity\\Blog', NULL, 'Cannot autowire service ".service_locator.VEHgvk6": it needs an instance of "App\\Entity\\Blog" but this type has been excluded because it\'s a Doctrine entity.'],
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
        ], [
            'blog' => 'App\\Entity\\Blog',
            'commentRepository' => 'App\\Repository\\CommentRepository',
        ]))->withContext('App\\Controller\\BlogController::exportBlogCommentsPdf()', $container);
    }
}
