<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.abbxjjx.App\Controller\BookingController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.abbxjjx.App\\Controller\\BookingController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'booking' => ['privates', '.errored..service_locator.abbxjjx.App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.abbxjjx": it needs an instance of "App\\Entity\\Booking" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'booking' => 'App\\Entity\\Booking',
        ]))->withContext('App\\Controller\\BookingController::show()', $container);
    }
}
