<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllerreactService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XjfKN7M.App\Controller\CommentController::react()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'comment' => ['privates', '.errored..service_locator.XjfKN7M.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.XjfKN7M": it needs an instance of "App\\Entity\\Comment" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\CommentController::react()', $container);

        if (isset($container->privates['.service_locator.XjfKN7M.App\\Controller\\CommentController::react()'])) {
            return $container->privates['.service_locator.XjfKN7M.App\\Controller\\CommentController::react()'];
        }

        return $container->privates['.service_locator.XjfKN7M.App\\Controller\\CommentController::react()'] = $instance;
    }
}
