<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCurrencyConverterServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CurrencyConverterService' shared autowired service.
     *
     * @return \App\Service\CurrencyConverterService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CurrencyConverterService.php';

        return $container->privates['App\\Service\\CurrencyConverterService'] = new \App\Service\CurrencyConverterService();
    }
}
