<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGamificationProgressServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GamificationProgressService' shared autowired service.
     *
     * @return \App\Service\GamificationProgressService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GamificationProgressService.php';

        return $container->privates['App\\Service\\GamificationProgressService'] = new \App\Service\GamificationProgressService(($container->privates['App\\Repository\\QuestRepository'] ?? $container->load('getQuestRepositoryService')), ($container->privates['App\\Repository\\UserQuestProgressRepository'] ?? $container->load('getUserQuestProgressRepositoryService')));
    }
}
