<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfferControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qcVv77R.App\Controller\OfferController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.qcVv77R'] ?? $container->load('get_ServiceLocator_QcVv77RService'));

        if (isset($container->privates['.service_locator.qcVv77R.App\\Controller\\OfferController::edit()'])) {
            return $container->privates['.service_locator.qcVv77R.App\\Controller\\OfferController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\OfferController::edit()', $container);

        if (isset($container->privates['.service_locator.qcVv77R.App\\Controller\\OfferController::edit()'])) {
            return $container->privates['.service_locator.qcVv77R.App\\Controller\\OfferController::edit()'];
        }

        return $container->privates['.service_locator.qcVv77R.App\\Controller\\OfferController::edit()'] = $instance;
    }
}
