<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertyControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E6bw2Nz.App\Controller\PropertyController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E6bw2Nz.App\\Controller\\PropertyController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'property' => ['privates', '.errored..service_locator.E6bw2Nz.App\\Entity\\Property', NULL, 'Cannot autowire service ".service_locator.E6bw2Nz": it needs an instance of "App\\Entity\\Property" but this type has been excluded because it\'s a Doctrine entity.'],
            'currencyConverter' => ['privates', 'App\\Service\\CurrencyConverterService', 'getCurrencyConverterServiceService', true],
        ], [
            'property' => 'App\\Entity\\Property',
            'currencyConverter' => 'App\\Service\\CurrencyConverterService',
        ]))->withContext('App\\Controller\\PropertyController::show()', $container);
    }
}
