<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProperty2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o9dFrnP.App\Entity\Property' shared service.
     *
     * @return \App\Entity\Property
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.o9dFrnP": it needs an instance of "App\\Entity\\Property" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
