<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertyControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o9dFrnP.App\Controller\PropertyController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.o9dFrnP'] ?? $container->load('get_ServiceLocator_O9dFrnPService'));

        if (isset($container->privates['.service_locator.o9dFrnP.App\\Controller\\PropertyController::delete()'])) {
            return $container->privates['.service_locator.o9dFrnP.App\\Controller\\PropertyController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\PropertyController::delete()', $container);

        if (isset($container->privates['.service_locator.o9dFrnP.App\\Controller\\PropertyController::delete()'])) {
            return $container->privates['.service_locator.o9dFrnP.App\\Controller\\PropertyController::delete()'];
        }

        return $container->privates['.service_locator.o9dFrnP.App\\Controller\\PropertyController::delete()'] = $instance;
    }
}
