<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EVb.jUj.App\Controller\ServiceController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.EVb.jUj'] ?? $container->load('get_ServiceLocator_EVb_JUjService'));

        if (isset($container->privates['.service_locator.EVb.jUj.App\\Controller\\ServiceController::edit()'])) {
            return $container->privates['.service_locator.EVb.jUj.App\\Controller\\ServiceController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\ServiceController::edit()', $container);

        if (isset($container->privates['.service_locator.EVb.jUj.App\\Controller\\ServiceController::edit()'])) {
            return $container->privates['.service_locator.EVb.jUj.App\\Controller\\ServiceController::edit()'];
        }

        return $container->privates['.service_locator.EVb.jUj.App\\Controller\\ServiceController::edit()'] = $instance;
    }
}
