<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._bhMPIo.App\Controller\TripController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._bhMPIo.App\\Controller\\TripController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trip' => ['privates', '.errored..service_locator._bhMPIo.App\\Entity\\Trip', NULL, 'Cannot autowire service ".service_locator._bhMPIo": it needs an instance of "App\\Entity\\Trip" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'trip' => 'App\\Entity\\Trip',
        ]))->withContext('App\\Controller\\TripController::show()', $container);
    }
}
