<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OllXBOR.App\Controller\TripController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.OllXBOR'] ?? $container->load('get_ServiceLocator_OllXBORService'));

        if (isset($container->privates['.service_locator.OllXBOR.App\\Controller\\TripController::delete()'])) {
            return $container->privates['.service_locator.OllXBOR.App\\Controller\\TripController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\TripController::delete()', $container);

        if (isset($container->privates['.service_locator.OllXBOR.App\\Controller\\TripController::delete()'])) {
            return $container->privates['.service_locator.OllXBOR.App\\Controller\\TripController::delete()'];
        }

        return $container->privates['.service_locator.OllXBOR.App\\Controller\\TripController::delete()'] = $instance;
    }
}
