<?php

namespace ContainerBJ731uJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BDSOZGB.App\Controller\UserController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.BDSOZGB.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.BDSOZGB": it needs an instance of "App\\Entity\\User" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'entityManager' => '?',
            'tokenStorage' => '?',
        ]))->withContext('App\\Controller\\UserController::delete()', $container);

        if (isset($container->privates['.service_locator.BDSOZGB.App\\Controller\\UserController::delete()'])) {
            return $container->privates['.service_locator.BDSOZGB.App\\Controller\\UserController::delete()'];
        }

        return $container->privates['.service_locator.BDSOZGB.App\\Controller\\UserController::delete()'] = $instance;
    }
}
