<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBJ731uJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBJ731uJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBJ731uJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBJ731uJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBJ731uJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'BJ731uJ',
    'container.build_id' => '4c963179',
    'container.build_time' => 1777101220,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBJ731uJ');
